#include "btree.h"

using std::cout;
using std::endl;

int main() {
  Btree bt;
  bt.insert(15);
  cout << "------" << endl;
  bt.show();
  bt.insert(7);
  cout << "------" << endl;
  bt.show();
  bt.insert(21);
  cout << "------" << endl;
  bt.show();
  bt.insert(2);
  cout << "------" << endl;
  bt.show();
  bt.insert(10);
  cout << "------" << endl;
  bt.show();
  bt.insert(17);
  cout << "------" << endl;
  bt.show();
  bt.insert(24);
  cout << "------" << endl;
  bt.show();
  bt.insert(1);
  cout << "------" << endl;
  bt.show();
  bt.insert(11);
  cout << "------" << endl;
  bt.show();
  bt.delete_(2);
  cout << "------" << endl;
  bt.show();
  bt.delete_(10);
  cout << "------" << endl;
  bt.show();
  bt.insert(16);
  cout << "------" << endl;
  bt.show();
  bt.insert(19);
  cout << "------" << endl;
  bt.show();
  bt.insert(18);
  cout << "------" << endl;
  bt.show();
  bt.insert(20);
  cout << "------" << endl;
  bt.show();
  bt.insert(23);
  cout << "------" << endl;
  bt.show();
  bt.insert(26);
  cout << "------" << endl;
  bt.show();
  bt.insert(25);
  cout << "------" << endl;
  bt.show();
  bt.insert(28);
  cout << "------" << endl;
  bt.show();
  bt.delete_(17);
  cout << "------" << endl;
  bt.show();
  bt.delete_(24);
  cout << "------" << endl;
  bt.show();
  cout << "------" << endl;
  bt.bfs();
  cout << "------" << endl;
  bt.my_bfs();
  return 0;
}
